import React from 'react';
import _ from 'underscore';
import { randomId } from './../../util/object';
import { patchedConsoleInstance as console } from './../../util/patched-console';

/**
 * Wraps a checkbox input to turn it into a toggle switch using CSS.
 * Use just like a checkbox input element.
 *
 * @prop {string} id - A unique id. If not supplied, one is autogenerated.
 * @prop {function} onChange - Change event handler.
 * @prop {boolean} checked - Whether is checked or not.
 */
export const Toggle = React.memo(function Toggle({ className, id, disabled, ...remainingProps }){
    const useID = id || randomId();
    return (
        <div className={"onoffswitch " + className + (disabled ? ' disabled' : '')}>
            <input type="checkbox" id={useID} {...remainingProps} className="onoffswitch-checkbox" disabled={disabled} />
            <label className="onoffswitch-label" htmlFor={id}>
                <span className="onoffswitch-inner"></span>
                <span className="onoffswitch-switch"></span>
            </label>
        </div>
    );
});
Toggle.defaultProps = {
    'name' : 'onoffswitch',
    'onChange' : function(e){
        console.log("Toggled ", this);
    },
    'id' : null,
    'checked' : false,
    'className' : ''
};
