---
# Generate a "latest" pre-release upon push to master.
# TODO: Add some unit testing to here later, perhaps.
# Workflow file based on demos from https://github.com/marketplace/actions/automatic-releases
# and CGAP main.yml
name: "pre-release"

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    runs-on: "ubuntu-latest"
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:

      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: false

      - name: "Install NPM dependencies"
        run: "npm ci"

      - name: "Build ES Modules (ESM) into es dir"
        run: "npm run build"

      - name: "Switch to Build Branch"
        run: "git fetch origin build && git checkout build"

      # - name: "Commit and Push Build Branch"
      #   run: "git "

      # - name: "Push to build branch"
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: self
      #     BRANCH: build
      #     FOLDER: "."
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     MESSAGE: "Build: ({sha}) {msg}"

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "./es/*" -f
          git commit -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "build"
          force: true


      # - name: "Zip Folder"
      #   run: "zip -r release.zip . -x \".git/*\" \".github/*\" \"node_modules/*\""

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Development Build"
      #     # Defining 'files' seems to move them up into "assets"
      #     # which is not desired.
      #     files: |
      #       release.zip
      #   id: "automatic_releases"
